export const products = [{
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        qty: 0,
        price: '16990000',
        discount: '44',
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: '',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '30',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: '',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: '',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: '',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '30',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: '',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: '',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: '',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '30',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: '',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: '',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
    {
        name: 'Card màn hình Colorful RTX 3060 NB DUO 12G V2 L - V',
        category: {
            name: 'Card đồ họa',
            tag: '#carddohoa',
        },
        // salePrice: price * discount / 100,
        price: '16990000',
        discount: '44',
        qty: 20,
        image: 'https://nguyenvu.store/wp-content/uploads/2022/07/vga-colorful-rtx-3060-nb-duo-12g-v2-l-v-01-510x510.jpg',
        noti: 'Giảm 500 khi build cùng PC',
    },
]