export const GET_PRODUCTS_PAGINATION = 'GET_PRODUCTS_PAGINATION';
export const GET_PRODUCTS_PAGINATION_SUCCESS = 'GET_PRODUCTS_PAGINATION_SUCCESS';
export const GET_PRODUCTS_PAGINATION_ERROR = 'GET_PRODUCTS_PAGINATION_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';